query getUserCurrent($userId: Uuid!) {
	user(userId: $userId) {
		userId
		albums {
			albumId
			title
		}
		current {
			songId
			mix
			title
			duration
			inLibrary(userId: $userId)
			featuring {
				artistId
				name
			}
			remixers {
				artistId
				name
			}
			artists {
				artistId
				name
			}
			genres {
				genreId
				name
			}
			album {
				albumId
				title
				cover(size: FULL)
			}
		}
	}
}
