query getSearch(
	$userId: Uuid!
	$query: String!
) {
  search(query: $query) {
    ...on Song {
      mix
      title
      songId
      duration
      inLibrary(userId: $userId)
      featuring {
        name
        artistId
      }
      remixers {
        name
        artistId
      }
      artists {
        name
        artistId
      }
      genres {
        name
        genreId
      }
      album {
        title
        albumId
        cover(size: HALF)
      }
    }
    ...on Genre {
      name
      genreId
    }
    ...on Album {
      albumId
      title
      released
      cover(size: HALF)
      artists {
        artistId
        name
      }
    }
    ...on Artist {
      name
      artistId
      songsTotal
      albumsTotal
      photo(size: MINI)
      inLibrary(userId: $userId)
    }
  }
}