query getArtists(
	$userId: Uuid!
	$page: NonNegativeInt!
	$orderBy: ArtistOrderByInput!
) {
	artists(
		page: $page
		orderBy: $orderBy
	) {
		name
		artistId
		songsTotal
		albumsTotal
		photo(size: MINI)
		inLibrary(userId: $userId)
	}
}