mutation updateUserCurrent($songId: Uuid!) {
  updateUserCurrent(songId: $songId) {
    userId
    current {
      songId
      mix
      title
      duration
      featuring {
        artistId
        name
      }
      remixers {
        artistId
        name
      }
      artists {
        artistId
        name
      }
      genres {
        genreId
        name
      }
      album {
        albumId
        title
      }
    }
  }
}
