mutation addUserArtist(
  $userId: Uuid!
  $artistId: Uuid!
) {
  addUserArtist(
    userId: $userId
    artistId: $artistId
  ) {
    artistId
    name
    songsTotal
    albumsTotal
    photo(size: MINI)
    dateAdded(userId: $userId)
    inLibrary(userId: $userId)
  }
}
