import queryDatabase from "./queryDatabase.js"

import {
  TABLE_PLAYS,
  TABLE_SONGS,
  TABLE_USERS,
  TABLE_ALBUMS,
  TABLE_GENRES,
  TABLE_ARTISTS,
  TABLE_PLAYLISTS,
  TABLE_USERS_NEXTS,
  TABLE_USERS_PREVS,
  TABLE_USERS_SONGS,
  TABLE_USERS_ALBUMS,
  TABLE_USERS_GENRES,
  TABLE_USERS_QUEUES,
  TABLE_SONGS_GENRES,
  TABLE_SONGS_ARTISTS,
  TABLE_USERS_ARTISTS,
  TABLE_ALBUMS_ARTISTS,
  TABLE_SONGS_REMIXERS,
  TABLE_PLAYLISTS_SONGS,
  TABLE_SONGS_FEATURING,
  TABLE_USERS_PLAYLISTS,
} from "../sql/index.js"

const queries = [
  TABLE_ARTISTS,
  TABLE_GENRES,
  TABLE_ALBUMS,
  TABLE_ALBUMS_ARTISTS,
  TABLE_SONGS,
  TABLE_SONGS_GENRES,
  TABLE_SONGS_ARTISTS,
  TABLE_SONGS_REMIXERS,
  TABLE_SONGS_FEATURING,
  TABLE_USERS,
  TABLE_USERS_NEXTS,
  TABLE_USERS_PREVS,
  TABLE_USERS_SONGS,
  TABLE_USERS_ALBUMS,
  TABLE_USERS_GENRES,
  TABLE_USERS_QUEUES,
  TABLE_USERS_ARTISTS,
  TABLE_PLAYLISTS,
  TABLE_PLAYLISTS_SONGS,
  TABLE_USERS_PLAYLISTS,
  TABLE_PLAYS,
]

const initializeTables = () => {
  queries.reduce(
    async (prev, next) => {
      try {
        await prev
      } catch (error) {
        throw new Error(error)
      }
      return queryDatabase({ query: next })
    },
    Promise.resolve(),
  )
}

export default initializeTables
