type Album {
	albumId: Uuid!
	title: String!
	released: Date!
	songs: [Song!]!
	genres: [Genre!]!
	artists: [Artist!]!
	totalPlays: NonNegativeInt!
	totalDuration: PositiveInt!
	userPlays(userId: Uuid!): [Play!]!
	cover(size: AlbumCoverSize!): Url!
	userPlaysTotal(userId: Uuid!): NonNegativeInt!
}