type Album {
  albumId: Uuid!
  title: String!
  songs: [Song!]!
  released: Date!
  genres: [Genre!]!
  artists: [Artist!]!
  totalDuration: PositiveInt!
  plays(userId: Uuid!): [Play!]!
  inLibrary(userId: Uuid!): Boolean!
  cover(size: AlbumCoverSize!): Url!
  dateAdded(userId: Uuid!): Timestamp
}