type Album {
	title: String!
	albumId: Uuid!
	released: Date!
	duration: PositiveInt!

	userPlays(userId: Uuid!): [Play!]!
	userPlaysTotal(userId: Uuid!): NonNegativeInt!
 
	songs: [Song!]! @cacheControl(maxAge: Infinity)
	genres: [Genre!]! @cacheControl(maxAge: Infinity)
	artists: [Artist!]! @cacheControl(maxAge: Infinity)
	playsTotal: NonNegativeInt! @cacheControl(maxAge: 300)
	songsTotal: NonNegativeInt! @cacheControl(maxAge: Infinity)
	cover(size: AlbumCoverSize!): Url! @cacheControl(maxAge: Infinity)
}