type Artist {
	name: String!
	artistId: Uuid!
	playsTotal: PositiveInt
	songsTotal: NonNegativeInt!
	albumsTotal: NonNegativeInt!
	inLibrary(userId: Uuid!): Boolean!
	userPlays(userId: Uuid!): [Play!]!
	photo(size: ArtistPhotoSize!): Url!
	dateAdded(userId: Uuid!): Timestamp
	songs(orderBy: SongOrderByInput!): [Song!]!
	userPlaysTotal(userId: Uuid!): NonNegativeInt
	albums(orderBy: AlbumOrderByInput!): [Album!]!
}