type Artist {
	name: String!
	artistId: Uuid!

	inLibrary(userId: Uuid!): Boolean!
	userPlays(userId: Uuid!): [Play!]!
	dateAdded(userId: Uuid!): Timestamp
	userPlaysTotal(userId: Uuid!): NonNegativeInt

	playsTotal: PositiveInt @cacheControl(maxAge: 300)
	songsTotal: NonNegativeInt! @cacheControl(maxAge: Infinity)
	albumsTotal: NonNegativeInt! @cacheControl(maxAge: Infinity)
	photo(size: ArtistPhotoSize!): Url! @cacheControl(maxAge: Infinity)
	songs(orderBy: SongOrderByInput!): [Song!]! @cacheControl(maxAge: Infinity)
	albums(orderBy: AlbumOrderByInput!): [Album!]! @cacheControl(maxAge: Infinity)
}