enum ArtistPhotoSize {
	MINI
	HALF
	FULL
}

enum AlbumCoverSize {
	HALF
	FULL
}

enum OrderByDirection {
	ASC
	DESC
}

enum SongOrderByField {
	TITLE
	ALBUM
	DURATION
	RELEASED
}

enum GenreOrderByField {
	NAME
}

enum AlbumOrderByField {
	TITLE
	RELEASED
}

enum ArtistOrderByField {
	NAME
}

enum PlaylistOrderByField {
	NAME
}

enum UserSongOrderByField {
	TITLE
	DURATION
	DATE_ADDED
}

enum UserArtistOrderByField {
	NAME
	DATE_ADDED
}

enum UserPlaylistOrderByField {
	NAME
	DATE_ADDED
}