type Genre {
	name: String!
	genreId: Uuid!
	numOfSongs: NonNegativeInt!
	playsTotal: NonNegativeInt!
	userPlays(userId: Uuid!): [Play!]!
	songs(orderBy: SongOrderByInput!): [Song!]!
	userPlaysTotal(userId: Uuid!): NonNegativeInt!
}