type Genre {
	name: String!
	genreId: Uuid!
	songsTotal: NonNegativeInt
	userPlays(userId: Uuid!): [Play!]
	songs(orderBy: SongOrderByInput!): [Song!]!
	userPlaysTotal(userId: Uuid!): NonNegativeInt
}