type Genre {
	name: String!
	genreId: Uuid!

	userPlays(userId: Uuid!): [Play!]
	userPlaysTotal(userId: Uuid!): NonNegativeInt

	playsTotal: NonNegativeInt! @cacheControl(maxAge: 300)
	songsTotal: PositiveInt @cacheControl(maxAge: Infinity)
	songs(orderBy: SongOrderByInput!): [Song!]! @cacheControl(maxAge: Infinity)
}