input ArtistInput {
	name: String!
	photo: Upload!
}

input GenreInput {
	name: String!
}

input AlbumInput {
	title: String!
	cover: Upload!
	released: Date!
	artists: [String!]!
	songs: [SongInput!]!
}

input SongInput {
	mix: String!
	title: String!
	audio: Upload!
	genres: [String!]!
	artists: [String!]!
	remixers: [String!]!
	featuring: [String!]!
	discNumber: PositiveInt!
	trackNumber: PositiveInt!
}

input PlaylistInput {
	title: String!
}

input UserInput {
	name: String!
}

input SongOrderByInput {
	field: SongOrderByField!
	direction: OrderByDirection!
}

input GenreOrderByInput {
	field: GenreOrderByField!
	direction: OrderByDirection!
}

input AlbumOrderByInput {
	field: AlbumOrderByField!
	direction: OrderByDirection!
}

input ArtistOrderByInput {
	field: ArtistOrderByField!
	direction: OrderByDirection!
}

input PlaylistOrderByInput {
	field: PlaylistOrderByField!
	direction: OrderByDirection!
}

input UserSongOrderByInput {
	field: UserSongOrderByField!
	direction: OrderByDirection!
}

input UserArtistOrderByInput {
	direction: OrderByDirection!
	field: UserArtistOrderByField!
}