type Mutation {
  userPrev(
    userId: Uuid!
  ): User!
  userPlay(
    docId: Uuid!
    userId: Uuid!
  ): User!
  userNext(
    userId: Uuid!
  ): User!
  userSongNext(
    userId: Uuid!
    songId: Uuid!
  ): User!
  userSongLater(
    userId: Uuid!
    songId: Uuid!
  ): User!
  userSongQueue(
    userId: Uuid!
    songId: Uuid!
  ): User!
  addUserSong(
    userId: Uuid!
    songId: Uuid!
  ): Song!
  addUserArtist(
    userId: Uuid!
    artistId: Uuid!
  ): Artist!
  rmUserSong(
    userId: Uuid!
    songId: Uuid!
  ): Song!
  rmUserArtist(
    userId: Uuid!
    artistId: Uuid!
  ): Artist!
  addUser(
    user: UserInput!
  ): User!
  add(
    genres: [GenreInput!]!
    albums: [AlbumInput!]!
    artists: [ArtistInput!]!
  ): String!
  addPlaylist(
    playlist: PlaylistInput!
  ): Playlist!
}