type Mutation {
  userPrev(
    userId: Uuid!
  ): User!
  updateUserCurrent(
    songId: Uuid!
    userId: Uuid!
  ): User!
  userNext(
    userId: Uuid!
  ): User!
  userSongNext(
    userId: Uuid!
    songId: Uuid!
  ): User!
  userSongAfter(
    userId: Uuid!
    songId: Uuid!
  ): User!
  userSongLater(
    userId: Uuid!
    songId: Uuid!
  ): User!
  userClearNext(
    userId: Uuid!
  ): User!
  userClearQueue(
    userId: Uuid!
  ): User!
  shuffleAlbum(
    userId: Uuid!
    albumId: Uuid!
  ): User!
  userShuffleLibrary(
    userId: Uuid!
  ): User!

  addUserSong(
    userId: Uuid!
    songId: Uuid!
  ): Song!
  rmUserSong(
    userId: Uuid!
    songId: Uuid!
  ): Song!
  addUserArtist(
    userId: Uuid!
    artistId: Uuid!
  ): Artist!
  rmUserArtist(
    userId: Uuid!
    artistId: Uuid!
  ): Artist!

  addUser(
    user: UserInput!
  ): User!
  add(
    genres: [GenreInput!]!
    albums: [AlbumInput!]!
    artists: [ArtistInput!]!
  ): String!
  addPlaylist(
    playlist: PlaylistInput!
  ): Playlist!
}