type Playlist {
	user: User!
	name: String!
	songs: [Song!]!
	playlistId: Uuid!
	dateCreated: Timestamp!
	playsTotal: NonNegativeInt!
	userPlays(userId: Uuid!): [Play!]!
	inLibrary(userId: Uuid!): Boolean!
	dateAdded(userId: Uuid!): Timestamp
	userPlaysTotal(userId: Uuid!): NonNegativeInt!
}