type Song {
	mix: String!
	songId: Uuid!
	title: String!
	size: PositiveInt!
	duration: PositiveInt!
	discNumber: PositiveInt!
	trackNumber: PositiveInt!

	album: Album! @cacheControl(maxAge: Infinity)
	genres: [Genre!]! @cacheControl(maxAge: Infinity)
	artists: [Artist!]! @cacheControl(maxAge: Infinity)
	remixers: [Artist!]! @cacheControl(maxAge: Infinity)
	featuring: [Artist!]! @cacheControl(maxAge: Infinity)
	playsTotal: NonNegativeInt @cacheControl(maxAge: 300)

	userPlays(userId: Uuid!): [Play!]!
	inLibrary(userId: Uuid!): Boolean!
	dateAdded(userId: Uuid!): Timestamp
	userPlaysTotal(userId: Uuid!): NonNegativeInt
	dateAddedToPlaylist(userId: Uuid!, playlistId: Uuid!): Timestamp
}