type User {
  userId: Uuid!
  name: String!
  current: Song
  email: Email!
  prev: [Song!]!
  next: [Song!]!
  queue: [Song!]!
  plays: [Play!]!
  dateJoined: Timestamp!
  songs(page: NonNegativeInt!, orderBy: UserSongOrderByInput!): [Song!]!
  albums(page: NonNegativeInt!, orderBy: UserAlbumOrderByInput!): [Album!]!
  artists(page: NonNegativeInt!, orderBy: UserArtistOrderByInput!): [Artist!]!
  playlists(page: NonNegativeInt!, orderBy: UserPlaylistOrderByInput!): [Playlist!]!
}