type User {
	userId: Uuid!
	name: String!
	email: Email!
	dateJoined: Timestamp!

	current: Song
	prev: [Song!]!
	next: [Song!]!
	later: [Song!]!
	plays: [Play!]!
	playsTotal: NonNegativeInt

	songsTotal: NonNegativeInt
	artistsTotal: NonNegativeInt

	songs(
		page: NonNegativeInt!
		orderBy: UserSongOrderByInput!
	): [Song!]!
	genres(
		page: NonNegativeInt!
		orderBy: GenreOrderByInput!
	): [Genre!]!
	albums(
		page: NonNegativeInt!
		orderBy: AlbumOrderByInput!
	): [Album!]!
	artists(
		page: NonNegativeInt!
		orderBy: UserArtistOrderByInput!
	): [Artist!]!
	playlists: [Playlist!]!
}