type User {
  userId: Uuid!
  name: String!
  current: Song
  prev: [Song!]!
  next: [Song!]!
  queue: [Song!]!
  plays: [Play!]!
  dateJoined: PositiveInt!
  songs(orderBy: UserSongOrderByInput!): [Song!]!
  albums(orderBy: UserAlbumOrderByInput!): [Album!]!
  artists(orderBy: UserArtistOrderByInput!): [Artist!]!
  playlists(orderBy: UserPlaylistOrderByInput!): [Playlist!]!
}