import componentClassNames from "../helpers/componentClassNames"

export const Album = componentClassNames("Album")
export const Albums = componentClassNames("Albums")
export const ApiError = componentClassNames("ApiError")
export const Artist = componentClassNames("Artist")
export const Artists = componentClassNames("Artists")
export const Catalog = componentClassNames("Catalog")
export const Add = componentClassNames("Add")
export const AddArtist = componentClassNames("AddArtist")
export const AddAlbum = componentClassNames("AddAlbum")
export const AddSong = componentClassNames("AddSong")
export const Empty = componentClassNames("Empty") 
export const Header = componentClassNames("Header")
export const Icon = componentClassNames("Icon")
export const Library = componentClassNames("Library")
export const LibraryArtists = componentClassNames("LibraryArtists")
export const LibraryAlbums = componentClassNames("LibraryAlbums")
export const LibrarySongs = componentClassNames("LibrarySongs")
export const Loading = componentClassNames("Loading")
export const Pages = componentClassNames("Pages")
export const Sidebar = componentClassNames("Sidebar")
export const Song = componentClassNames("Song")
export const Songs = componentClassNames("Songs")
