query getUserPage($userId: Uuid!) {
  user(userId: $userId) {
    name
    userId
    songsTotal
    artistsTotal
    playlists(
      page: 1
      orderBy: {
        field: TITLE
        direction: ASC
      }
    ) {
      playlistId
      title
    }
  }
}
