mutation addAlbum(
  $cover: Upload!,
  $title: String!,
  $artists: [Uuid!]!,
  $released: String!,
) {
  addAlbum(album: {
    cover: $cover,
    title: $title,
    artists: $artists,
    released: $released,
  }) {
    albumId
  }
}
