mutation addAlbum(
  $cover: Upload!,
  $title: String!,
  $released: String!,
  $artistIds: [Uuid!]!,
) {
  addAlbum(album: {
    cover: $cover,
    title: $title,
    released: $released,
    artistIds: $artistIds,
  }) {
    albumId
  }
}
