mutation addAlbum(
  $cover: Upload!,
  $title: String!,
  $released: Int!,
  $artists: [Uuid!]!,
) {
  addAlbum(album: {
    cover: $cover,
    title: $title,
    artists: $artists,
    released: $released,
  }) {
    title
    albumId
  }
}
