mutation addSong(
  $mix: String!
  $albumId: Uuid!
  $audio: Upload!
  $title: String!
  $genreIds: [Uuid!]!
  $artistIds: [Uuid!]!
  $remixerIds: [Uuid!]!
  $featuringIds: [Uuid!]!
  $discNumber: PositiveInt!
  $trackNumber: PositiveInt!
) {
  addSong(song: {
    mix: $mix
    audio: $audio
    title: $title
    albumId: $albumId
    genreIds: $genreIds
    artistIds: $artistIds
    remixerIds: $remixerIds
    discNumber: $discNumber
    trackNumber: $trackNumber
    featuringIds: $featuringIds
  }) {
    songId
  }
}
