mutation addSong(
  $mix: String!
  $album: Uuid!
  $audio: Upload!
  $title: String!
  $genres: [Uuid!]!
  $artists: [Uuid!]!
  $remixers: [Uuid!]!
  $featuring: [Uuid!]!
  $discNumber: PositiveInt!
  $trackNumber: PositiveInt!
) {
  addSong(song: {
    mix: $mix
    audio: $audio
    title: $title
    album: $album
    genres: $genres
    artists: $artists
    remixers: $remixers
    featuring: $featuring
    discNumber: $discNumber
    trackNumber: $trackNumber
  }) {
    songId
    title
  }
}
