type Artist {
  name: String!
  artistId: Uuid!
  songs: [Song!]!
  albums: [Album!]!
  numOfSongs: NonNegativeInt!
  numOfAlbums: NonNegativeInt!
  plays(userId: Uuid!): [Play!]
  inLibrary(userId: Uuid!): Boolean!
  dateAdded(userId: Uuid!): PositiveInt
  photo(size: ArtistPhotoSizes!): String!
}
