type Artist {
  name: String!
  artistId: Uuid!
  albums: [Album!]!
  numOfPlays: Int!,
  numOfSongs: NonNegativeInt!
  numOfAlbums: NonNegativeInt!
  plays(userId: Uuid!): [Play!]
  inLibrary(userId: Uuid!): Boolean!
  dateAdded(userId: Uuid!): PositiveInt
  songs(orderBy: SongOrderByInput!): [Song!]!
  photo(size: ArtistPhotoSize! = HALF): String!
}
