enum ArtistPhotoSize {
  MINI
  HALF
  FULL
}

enum AlbumCoverSize {
  HALF
  FULL
}

enum OrderByDirection {
  ASC
  DESC
}

enum SongOrderByField {
  TITLE
  DURATION
}

enum UserSongOrderByField {
	TITLE
  DURATION
	DATE_ADDED
}

enum GenreOrderByField {
  NAME
}

enum UserGenreOrderByField {
  NAME
  DATE_ADDED
}

enum ArtistOrderByField {
  NAME
}

enum UserArtistOrderByField {
  NAME
  DATE_ADDED
}

enum AlbumOrderByField {
  TITLE
  RELEASED
}

enum UserAlbumOrderByField {
  TITLE
  RELEASED
  DATE_ADDED
}

enum PlaylistOrderByField {
  NAME
}

enum UserPlaylistOrderByField {
  NAME
  DATE_ADDED
}