enum ArtistPhotoSize {
  MINI
  HALF
  FULL
}

enum AlbumCoverSize {
  HALF
  FULL
}

enum OrderByDirection {
  ASC
  DESC
}

enum SongOrderField {
  TITLE
  DURATION
}

enum GenreOrderField {
  NAME
}
