input UserInput {
	name: String!
	email: Email!
}

input ArtistInput {
	name: String!
	photo: Upload!
}

input GenreInput {
	name: String!
}

input AlbumInput {
	title: String!
	cover: Upload!
	artists: [Uuid!]!
	released: String!
}

input SongInput {
	mix: String!
	album: Uuid!
	title: String!
	audio: Upload!
	genres: [Uuid!]!
	artists: [Uuid!]!
	remixers: [Uuid!]!
	featuring: [Uuid!]!
	discNumber: PositiveInt!
	trackNumber: PositiveInt!
}

input PlaylistInput {
	user: Uuid!
  name: String!
  songs: [Uuid!]!
}

input SongOrderByInput {
	field: SongOrderByField!
	direction: OrderByDirection!
}

input UserSongOrderByInput {
	field: UserSongOrderByField!
	direction: OrderByDirection!
}

input ArtistOrderByInput {
	field: ArtistOrderByField!
	direction: OrderByDirection!
}

input UserArtistOrderByInput {
	direction: OrderByDirection!
	field: UserArtistOrderByField!
}

input AlbumOrderByInput {
	field: AlbumOrderByField!
	direction: OrderByDirection!
}

input UserAlbumOrderByInput {
	direction: OrderByDirection!
	field: UserAlbumOrderByField!
}

input PlaylistOrderByInput {
	field: PlaylistOrderByField!
	direction: OrderByDirection!
}

input UserPlaylistOrderByInput {
	direction: OrderByDirection!
	field: UserPlaylistOrderByField!
}