type Mutation {
  userPrev(
    userId: Uuid!
  ): User!
  userPlay(
    docId: Uuid!
    userId: Uuid!
  ): User!
  userNext(
    userId: Uuid!
  ): User!
  userAddSongNext(
    userId: Uuid!
    songId: Uuid!
  ): User!
  userAddSongLater(
    userId: Uuid!
    songId: Uuid!
  ): User!
  userAddSongQueue(
    userId: Uuid!
    songId: Uuid!
  ): User!
  addUserSong(
    userId: Uuid!
    songId: Uuid!
  ): Song!
  addUserAlbum(
    userId: Uuid!
    albumId: Uuid!
  ): Album!
  addUserGenre(
    userId: Uuid!
    genreId: Uuid!
  ): Genre!
  addUserArtist(
    userId: Uuid!
    artistId: Uuid!
  ): Artist!
  rmUserSong(
    userId: Uuid!
    songId: Uuid!
  ): Song!
  rmUserAlbum(
    userId: Uuid!
    albumId: Uuid!
  ): Album!
  rmUserGenre(
    userId: Uuid!
    genreId: Uuid!
  ): Genre!
  rmUserArtist(
    userId: Uuid!
    artistId: Uuid!
  ): Artist!
  addUser(user: UserInput!): User!
  addSong(song: SongInput!): Song!
  addGenre(genre: GenreInput!): Genre!
  addAlbum(album: AlbumInput!): Album!
  addArtist(artist: ArtistInput!): Artist!
  addPlaylist(playlist: PlaylistInput!): Playlist!
}
