type Query {
  # database
  songs: [Song!]!
  albums: [Album!]!
  genres: [Genre!]!
  artists: [Artist!]!
  playlists: [Playlist!]!
  user(userId: Uuid!): User!
  play(playId: Uuid!): Play!
  song(songId: Uuid!): Song!
  album(albumId: Uuid!): Album!
  genre(genreId: Uuid!): Genre!
  artist(artistId: Uuid!): Artist!
  playlist(playlistId: Uuid!): Playlist!

  # misc queries
  newAlbums: [Album!]!
  topTenSongs: [Song!]!
  parseUrl(url: String!): String!
  albumReleased(title: String!): Int
  imageSearch(query: String!): String!
  parseSongs(files: [Upload!]!): Json!
  
  # search
  songSearch(query: String!, exact: Boolean = false): [Song!]!
  albumSearch(query: String!, exact: Boolean = false): [Album!]!
  genreSearch(query: String!, exact: Boolean = false): [Genre!]!
  artistSearch(query: String!, exact: Boolean = false): [Artist!]!
  genreSearchExact(query: String!, exact: Boolean = false): Genre
  artistSearchExact(query: String!, exact: Boolean = false): Artist
}
