type Query {
  # database
  songs: [Song!]!
  albums: [Album!]!
  genres: [Genre!]!
  artists: [Artist!]!
  playlists: [Playlist!]!
  user(userId: Uuid!): User!
  play(playId: Uuid!): Play!
  song(songId: Uuid!): Song!
  album(albumId: Uuid!): Album!
  genre(genreId: Uuid!): Genre!
  artist(artistId: Uuid!): Artist!
  playlist(playlistId: Uuid!): Playlist!
  
  #search
  songSearch(query: String!): [Song!]!
  albumSearch(query: String!): [Album!]!
  genreSearch(query: String!): [Genre!]!
  artistSearch(query: String!): [Artist!]!

  # miscellaneous queries
  newAlbums: [Album!]!
  topTenSongs: [Song!]!
  parseSongs(files: [Upload!]!): Json!
  albumReleased(title: String!): Int
}
