type Query {
  # database
  user(userId: Uuid!): User!
  play(playId: Uuid!): Play!
  song(songId: Uuid!): Song!
  album(albumId: Uuid!): Album!
  genre(genreId: Uuid!): Genre!
  artist(artistId: Uuid!): Artist!
  playlist(playlistId: Uuid!): Playlist!
  albums: [Album!]!
  playlists: [Playlist!]!
  songs(orderBy: SongOrderByInput!): [Song!]!
  genres(orderBy: GenreOrderByInput!): [Genre!]!
  artists(orderBy: ArtistOrderByInput!): [Artist!]!

  # misc queries
  newAlbums: [Album!]!
  topTenSongs: [Song!]!
  parseUrl(url: String!): String!
  parseSong(file: Upload!): Json!
  imageSearch(query: String!): String!
  albumReleased(title: String!): PositiveInt
  
  # search
  songSearch(query: String!, exact: Boolean = false): [Song!]!
  albumSearch(query: String!, exact: Boolean = false): [Album!]!
  genreSearch(query: String!, exact: Boolean = false): [Genre!]!
  artistSearch(query: String!, exact: Boolean = false): [Artist!]!
  genreSearchExact(query: String!, exact: Boolean = false): Genre
  artistSearchExact(query: String!, exact: Boolean = false): Artist
}
