query getSongPage(
  $userId: Uuid!
  $songId: Uuid!
) {
  song(songId: $songId) {
    bpm
    size
    title
    songId
    duration
    playsTotal
    inLibrary(userId: $userId)
    key {
      keyId
      flatName
      sharpName
      camelotName
    }
    featuring {
      name
      artistId
    }
    remixers {
      name
      artistId
    }
    artists {
      name
      artistId
    }
    genres {
      name
      genreId
    }
    album {
      title
      albumId
      released
      cover(size: HALF)
    }
    userPlays(userId: $userId) {
      playId
      dateCreated
    }
  }
}
