query albums(
  $page: NonNegativeInt!
  $orderBy: AlbumOrderByInput!
) {
  albums(
    page: $page
    orderBy: $orderBy
  ) {
    albumId
    title
    released
    cover(size: HALF)
    artists {
      artistId
      name
    }
  }
}
