query getAlbumPage(
  $userId: Uuid!
  $albumId: Uuid!
) {
  album(albumId: $albumId) {
    albumId
    title
    released
    duration
    cover(size: FULL)
    genres {
      name
      genreId
    }
    artists {
      name
      artistId
    }
    songs {
      songId
      mix
      title
      duration
      discNumber
      trackNumber
      inLibrary(userId: $userId)
      featuring {
        artistId
        name
      }
      remixers {
        artistId
        name
      }
      artists {
        artistId
        name
      }
      genres {
        genreId
        name
      }
      album {
        albumId
        title
      }
    }
  }
}
