query artists(
  $userId: Uuid!
  $page: NonNegativeInt!
  $orderBy: ArtistOrderByInput!
) {
  artists(
    page: $page
    orderBy: $orderBy
  ) {
    name
    artistId
    numOfSongs
    numOfAlbums
    photo(size: MINI)
    inLibrary(userId: $userId)
  }
}
