query artistPage(
  $userId: Uuid!
  $artistId: Uuid!
) {
  artist(artistId: $artistId) {
    artistId
    name
    numOfPlays
    numOfSongs
    numOfAlbums
    photo(size: FULL)
    inLibrary(userId: $userId)
  }
}
