query artists(
  $userId: Uuid!
  $orderBy: ArtistOrderByInput!
) {
  artists(orderBy: $orderBy) {
    artistId
    name
    numOfSongs
    numOfAlbums
    photo(size: MINI)
    inLibrary(userId: $userId)
  }
}
