query artistPage(
  $userId: Uuid!
  $artistId: Uuid!
  $songsOrderBy: SongOrderByInput!
  $albumsOrderBy: AlbumOrderByInput!
) {
  artist(artistId: $artistId) {
    artistId
    name
    numOfPlays
    photo(size: FULL)
    inLibrary(userId: $userId)
    songs(orderBy: $songsOrderBy) {
      songId
      mix
      title
      duration
      inLibrary(userId: $userId)
      featuring {
        artistId
        name
      }
      remixers {
        artistId
        name
      }
      artists {
        artistId
        name
      }
      genres {
        genreId
        name
      }
      album {
        albumId
        title
        released
        cover(size: HALF)
        inLibrary(userId: $userId)
      }
    }
    albums(orderBy: $albumsOrderBy) {
      albumId
      title
      cover(size: HALF)
      inLibrary(userId: $userId)
      artists {
        artistId
        name
      }
    }
  }
}
