query genrePage($genreId: Uuid!) {
  genre(genreId: $genreId) {
    genreId
    name
    songs {
      songId
      title
      mix
      duration
      featuring {
        artistId
        name
      }
      remixers {
        artistId
        name
      }
      artists {
        artistId
        name
      }
      album {
        albumId
        title
        cover(size: HALF)
      }
      genres {
        genreId
        name
      }
    }
  }
}
