query getArtistPage(
  $userId: Uuid!
  $artistId: Uuid!
) {
  artist(artistId: $artistId) {
    artistId
    name
    photo(size: FULL)
    inLibrary(userId: $userId)
    songs {
      songId
      mix
      title
      duration
      inLibrary(userId: $userId)
      featuring {
        artistId
        name
      }
      remixers {
        artistId
        name
      }
      artists {
        artistId
        name
      }
      genres {
        genreId
        name
      }
      album {
        albumId
        title
        released
        cover(size: HALF)
      }
    }
    albums {
      albumId
      title
      cover(size: HALF)
      inLibrary(userId: $userId)
      artists {
        artistId
        name
      }
    }
  }
}
