query getSongs($userId: ID!) {
  songs {
    songId
    title
    mix
    duration
    inLibrary(userId: $userId)
    isCurrent(userId: $userId)
    featuring {
      artistId
      name
    }
    remixers {
      artistId
      name
    }
    artists {
      artistId
      name
    }
    genres {
      genreId
      name
    }
    album {
      albumId
      title
    }
  }
}
