query getUserArtists($userId: Uuid!) {
  user(userId: $userId) {
    userId
    artists {
      artistId
      name
      photo
      inLibrary(userId: $userId)
      dateAdded(userId: $userId)
    }
  }
}
