query song(
  $userId: Uuid!
  $songId: Uuid!
) {
  song(songId: $songId) {
    size
    title
    songId
    duration
    inLibrary(userId: $userId)
    featuring {
      name
      artistId
    }
    remixers {
      name
      artistId
    }
    artists {
      name
      artistId
    }
    genres {
      name
      genreId
    }
    album {
      title
      albumId
      released
      cover(size: HALF)
    }
    plays(userId: $userId) {
      playId
      dateCreated
    }
    totalPlays {
      playId
    }
  }
}
