query songs(
  $userId: Uuid!
  $page: NonNegativeInt!
  $orderBy: SongOrderByInput!
) {
  songs(
    page: $page
    orderBy: $orderBy
  ) {
    mix
    title
    songId
    duration
    inLibrary(userId: $userId)
    featuring {
      name
      artistId
    }
    remixers {
      name
      artistId
    }
    artists {
      name
      artistId
    }
    genres {
      name
      genreId
    }
    album {
      title
      albumId
      cover(size: HALF)
    }
  }
}
