query songs($userId: Uuid!) {
  songs {
    mix
    title
    songId
    duration
    inLibrary(userId: $userId)
    isCurrent(userId: $userId)
    featuring {
      name
      artistId
    }
    remixers {
      name
      artistId
    }
    artists {
      name
      artistId
    }
    genres {
      name
      genreId
    }
    album {
      title
      albumId
      cover(size: HALF)
    }
  }
}
