query userGenres(
  $userId: Uuid!
  $orderBy: UserGenreOrderByInput!
) {
  user(userId: $userId) {
    userId
    genres(orderBy: $orderBy) {
      genreId
      name
      dateAdded(userId: $userId)
      inLibrary(userId: $userId)
    }
  }
}
