query userArtists(
  $userId: Uuid!
  $page: NonNegativeInt!
  $orderBy: UserArtistOrderByInput!
) {
  user(userId: $userId) {
    userId
    artists(page: $page, orderBy: $orderBy) {
      artistId
      name
      photo(size: MINI)
      dateAdded(userId: $userId)
      inLibrary(userId: $userId)
    }
  }
}
