query userAlbums(
  $userId: Uuid!
  $orderBy: UserAlbumOrderByInput!
) {
  user(userId: $userId) {
    userId
    albums(orderBy: $orderBy) {
      albumId
      title
      cover(size: HALF)
      dateAdded(userId: $userId)
      artists {
        artistId
        name
      }
    }
  }
}
